//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Post
    {
        public int Id { get; set; }
        public string SlugUrl { get; set; }
        public string Name { get; set; }
        public Nullable<int> CateId { get; set; }
        public string Title { get; set; }
        public string Url { get; set; }
        public string Image { get; set; }
        public string Keywords { get; set; }
        public string Description { get; set; }
        public string Contents { get; set; }
        public string Status { get; set; }
        public string Type { get; set; }
        public string Tags { get; set; }
        public string FaceIds { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<int> CountView { get; set; }
    }
}
